In [21]:
import cv2
import torch
import torch.nn as nn
import numpy as np
from torchvision import datasets, transforms, models
import os
import matplotlib.pyplot as plt
import json
import csv
from PIL import Image
import pandas as pd

In [24]:

data_path= "/home/ubuntu/hi-env/image-processing-labs/end-project/nyamka-and-idree/faces/data/"
old_path= "/home/ubuntu/hi-env/image-processing-labs/end-project/nyamka-and-idree/faces/+25/"
young_path= "/home/ubuntu/hi-env/image-processing-labs/end-project/nyamka-and-idree/faces/-25/"

In [3]:
def get_all_images(folder, ext):
    return [os.path.join(folder, f) for f in os.listdir(folder) if f.endswith(".jpg")]

In [4]:

data = get_all_images(data_path, 'jpg')

In [25]:
old = get_all_images(old_path, 'jpg')
young = get_all_images(young_path, 'jpg')
old_train = np.array([cv2.imread(jpg) for jpg in old])
young_train = np.array([cv2.imread(jpg) for jpg in young])
size = 28
old_tr = [cv2.resize(x, (size, size)) for x in old_train]
young_tr = [cv2.resize(x, (size, size)) for x in young_train]


In [5]:
data_train = np.array([cv2.imread(jpg) for jpg in data])

In [28]:
old_tr[150].shape

(28, 28, 3)

In [19]:
data_train[0][1]

array([[ 94, 125, 124],
       [ 94, 125, 124],
       [ 96, 124, 124],
       [ 98, 126, 126],
       [ 99, 127, 128],
       [100, 128, 129],
       [100, 128, 129],
       [101, 129, 130],
       [101, 129, 130],
       [102, 130, 131],
       [104, 131, 135],
       [106, 133, 137],
       [104, 133, 137],
       [104, 133, 137],
       [105, 134, 138],
       [106, 135, 139],
       [105, 134, 139],
       [106, 135, 140],
       [107, 136, 141],
       [107, 136, 141],
       [106, 136, 141],
       [106, 136, 141],
       [104, 136, 141],
       [105, 137, 142],
       [105, 137, 142],
       [104, 136, 141],
       [104, 136, 141],
       [104, 136, 141],
       [103, 136, 139],
       [103, 136, 139],
       [104, 137, 140],
       [103, 136, 139],
       [103, 135, 140],
       [101, 133, 138],
       [ 99, 131, 137],
       [ 90, 124, 130],
       [ 85, 119, 125],
       [ 73, 105, 111],
       [ 58,  87,  94],
       [ 45,  71,  77],
       [ 30,  50,  55],
       [ 23,  41

In [12]:
# with open('train_datas.csv', mode='w') as train:
#     train_writer = csv.writer(train, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)

#     train_writer.writerow(['labels', 'pixels'])
#     for i in range(0,len(old_train)):
#         train_writer.writerow(['0', old_train[i]])
#     for j in range(0,len(young_train)):
#         train_writer.writerow(['1', young_train[j]])
for d in data:   
    img_file = Image.open(d)
    # img_file.show()

    # get original image parameters...
    width, height = img_file.size
    format = img_file.format
    mode = img_file.mode

    # Make image Greyscale
    img_grey = img_file.convert('L')
    #img_grey.save('result.png')
    #img_grey.show()

    # Save Greyscale values
    value = np.asarray(img_grey.getdata(), dtype=np.int).reshape((img_grey.size[1], img_grey.size[0]))
    value = value.flatten()
    with open("img_pixels.csv", 'a') as f:
        
        writer = csv.writer(f)
        writer.writerow(value)
        for i in range(0, 784):
            writer.writerow
            

[122 121 121 ... 171 172 176]
[91 87 91 ... 90 91 91]
[134 134 134 ... 125 125 124]
[121 122 122 ... 110 112 112]
[112 112 111 ... 112 112 112]
[ 96  95  94 ... 114 145 168]
[109 109 107 ...  98  98  97]
[143 141 141 ... 113 113 113]
[39 39 39 ... 45 40 46]
[111 112 113 ...  94  92  92]
[70 71 75 ... 41 40 38]
[220 224 232 ... 132 132 132]
[43 43 44 ... 35 35 34]
[148 152 153 ... 135 134 134]
[129 129 127 ...  90  90  91]
[115 115 114 ...  83  82  81]
[142 143 144 ...  18  18  17]
[229 229 230 ...  74  76  76]
[181 199 213 ...  74  75  75]
[116 111 110 ... 103 104 107]
[111 111 108 ...  76  75  76]
[70 67 61 ... 51 50 48]
[116 118 120 ...  72  73  73]
[86 87 87 ... 31 39 35]
[117 117 117 ... 193 199 202]
[43 43 43 ... 70 71 72]
[160 162 165 ... 237 240 242]
[244 245 242 ... 152 149 149]
[139 141 142 ... 126 126 127]
[125 123 124 ... 123 122 121]
[83 84 84 ... 70 70 70]
[218 219 207 ...  93  94  94]
[148 148 148 ... 139 139 139]
[72 71 71 ... 50 45 42]
[68 68 68 ... 86 86 87]
[134 133 1

[120 120 120 ... 134 135 135]
[161 157 154 ...  77  78  76]
[47 46 48 ... 97 97 97]
[136 136 134 ...  42  50  65]
[116 116 115 ... 104 104 104]
[156 160 162 ... 143 134 134]
[136 135 135 ... 121 120 119]
[137 137 138 ...  40  36  41]
[24 22 20 ... 39 40 41]
[33 29 29 ... 19 20 21]
[70 74 79 ... 54 51 52]
[ 90  89  90 ... 194 196 198]
[148 150 150 ... 237 238 238]
[145 144 145 ... 130 130 131]
[60 53 46 ... 57 57 58]
[134 134 134 ...   4   5   5]
[128 129 131 ... 233 231 227]
[243 242 241 ... 127 127 128]
[237 236 234 ... 125 125 126]
[ 38  41  42 ... 106 106 107]
[235 229 213 ... 111 111 110]
[146 146 146 ... 137 136 136]
[147 148 148 ... 133 133 134]
[117 119 119 ...  78  80  82]
[81 80 81 ... 50 49 50]
[156 156 155 ... 124 122 121]
[132 133 134 ... 118 119 118]
[125 124 123 ... 110 109 109]
[252 215  43 ...  30  12  31]
[99 98 98 ... 55 60 61]
[90 91 91 ... 90 90 91]
[140 143 141 ...  50  50  50]
[129 129 129 ...  64  83  87]
[120 122 122 ... 109 102 103]
[124 124 123 ...  86  89  92

In [22]:
df = pd.read_csv('/home/ubuntu/hi-env/image-processing-labs/end-project/nyamka-and-idree/img_pixels.csv')
print(df.shape)
df.head()

(389, 90000)


122  121  121.1  122.1  123  125  125.1  126  125.2  127  ...  175.899  \
0   91   87     91     90   85   89     94   89     85   72  ...       91   
1  134  134    134    133  133  133    133  133    134  131  ...      127   
2  121  122    122    121  120  121    122  122    122  122  ...      109   
3  112  112    111    110  110  109    105  102     98   94  ...      114   
4   96   95     94     94  102  115    118  110     99   95  ...       52   

   176.910  176.911  175.900  174.866  173.817  171.859  171.860  172.836  \
0       91       91       90       90       90       89       90       91   
1      126      126      125      125      125      125      125      125   
2      109      109      108      109      109      110      110      112   
3      114      113      114      114      113      112      112      112   
4       53       55       55       58       64       87      114      145   

   176.912  
0       91  
1      124  
2      112  
3      112  
4      168  

[5 rows x 90000 columns]

In [39]:
with open('eggs.csv', 'w', newline='') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter=' ',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    spamwriter.writerow(['Spam'] * 5 + ['Baked Beans'])
    spamwriter.writerow(['Spam', 'Lovely Spam', 'Wonderful Spam'])