In [68]:
import torchvision.models as models
import torchvision.transforms as transforms
import torchvision.datasets as datasets
import cv2
from glob import glob
import numpy as np
import torch
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import cosine_distances

## Preprocessing

In [33]:
size = 256
transform = transforms.Compose([
    transforms.ToTensor(),
])

In [104]:
dogs_dir = glob('./data/dog-or-cat/dog/*')
cats_dir = glob('./data/dog-or-cat/cat/*')

In [105]:
dogs = [cv2.imread(x) for x in dogs_dir]
cats = [cv2.imread(x) for x in cats_dir]

In [106]:
dogs = [cv2.resize(x, (size, size)) for x in dogs]
cats = [cv2.resize(x, (size, size)) for x in cats]

In [107]:
# one shot learning
dogs_gray = [cv2.cvtColor(x, cv2.COLOR_BGR2GRAY) for x in dogs]
cats_gray = [cv2.cvtColor(x, cv2.COLOR_BGR2GRAY) for x in cats]

In [108]:
dogs[0].shape

(256, 256, 3)

In [109]:
cosine_similarity(dogs_gray[0], dogs_gray[0]).shape

(256, 256)

In [110]:
dogs = [transform(x) for x in dogs]
cats = [transform(x) for x in cats]

In [49]:
dogs[0].shape

torch.Size([3, 256, 256])

## Feature Extraction

In [111]:
resnet18 = models.resnet18(pretrained=True)

In [112]:
dog_features = [resnet18(torch.unsqueeze(x, 0)) for x in dogs]
cat_features = [resnet18(torch.unsqueeze(x, 0)) for x in cats]

In [113]:
# converting back to numpy array
dog_features = [x.detach().numpy() for x in dog_features]
cat_features = [x.detach().numpy() for x in cat_features]

In [114]:
cosine_similarity(dog_features[0], dog_features[0])

array([[0.9999999]], dtype=float32)

In [116]:
cosine_similarity(cat_features[0], dog_features[0])

array([[0.99484825]], dtype=float32)

### RESNET 50

In [117]:
resnet = models.resnet50(pretrained=True)

In [118]:
dog_features = [resnet(torch.unsqueeze(x, 0)) for x in dogs]
cat_features = [resnet(torch.unsqueeze(x, 0)) for x in cats]

In [122]:
# converting back to numpy array
dog_features = [x.detach().numpy() for x in dog_features]
cat_features = [x.detach().numpy() for x in cat_features]

In [126]:
cosine_similarity(dog_features[0], dog_features[1])

array([[0.98875344]], dtype=float32)

In [125]:
cosine_similarity(cat_features[0], dog_features[0])

array([[0.98948175]], dtype=float32)